### ISSUE TITLE
Project in Swift?

### ISSUE THREAD

**Issue by AAAstorga** [firebase/friendlypix-ios#1]
Is it possible to have this project ported to Swift? I do think it is super valuable to see how to properly use the Firebase tools, but objective-c is getting outdated. I would love to see this ported to Swift to have a more capable understanding of using the Firebase suite.

**Comment by ulukaya** [comment]
Creating a rewrite with Swift indeed, hoping to release in a week or two.

**Comment by yamoridon** [comment]
Hi, I made a Swift port!
https://github.com/yamoridon/friendlypix-swift

Yes, this doesn't use Realtime Database and UITableView efficiently, but it works!

**Comment by ulukaya** [comment]
Just pushed out the Swift version. There are couple things I want to fix, but didn't want to delay the push.

**Comment by yamoridon** [comment]
Great! Thank you for the update!
