### ISSUE TITLE
Add a flag that specifies with which client was a post created

### ISSUE THREAD

**Issue by nicolasgarnier** [firebase/friendlypix-ios#10]
On the web i started adding an attribute to posts that specifies which client wrote the post. Valid values are `web`, `ios` and `android`:

![image](https://user-images.githubusercontent.com/3766663/38741488-51600522-3f3a-11e8-868e-89d0c1774152.png)

Could you add the `client: "ios"` attribute for each posts created via the iOS app for tracking and debugging purposes?

**Comment by ulukaya** [comment]
fixed in https://github.com/firebase/friendlypix-ios/commit/8606c01e753cba94cdb096cf1bcf329761c6294b
