### ISSUE TITLE
it works ??

### ISSUE THREAD

**Issue by blondie63** [firebase/friendlypix-ios#22]
I've tried it but there's a lot of warning (102), app start with main logo on center but i can do nothing..
No error, no login page..

whats wrong ?

**Comment by ulukaya** [comment]
warnings are coming from the dependency pods. Are you sure you are setting up your own Firebase project as in https://github.com/firebase/friendlypix-ios/blob/master/README.md

**Comment by ulukaya** [comment]
you can also see the working version on https://itunes.apple.com/us/app/friendlypix/id1318492920?mt=8

**Comment by blondie63** [comment]
Hi, i've done some test 15 days ago and i've setup my Firebase prj
Anyway, i'll try again later
thanks
