### ISSUE TITLE
No REVERSED_CLIENT_ID

### ISSUE THREAD

**Issue by shingetzu** [firebase/friendlypix-ios#3]
Hi,  I'm following the guide in the readme file and in the google sign up method, it says to replace the REVERSED_CLIENT_ID in info.plist.  I can see it in googleservice-info.plist but there is no REVERSED_CLIENT_ID in info.plist.  I tried adding it but there's no option for it so I just created it.  I tried running the app and it crashes because of this.  What to do?

**Comment by ajaybeniwal** [comment]
It is mentioned in the URL Types in URL Scheme there you can update the key value
