### ISSUE TITLE
Build Error - FPCommentCell.swift:20 "Cannot inherit from non-open class 'MDCSelfSizingStereoCell' outside of its defining module"

### ISSUE THREAD

**Issue by dweekly** [firebase/friendlypix-ios#42]
Fresh pod repo update && pod install, then build and run in XCode 10.2.1 on macOS 10.14.5

**Comment by mjzandona** [comment]
rebuild as swift 4.2.  issue happens in swift 5.

**Comment by machive** [comment]
Any update on this issue? Will this be fixed for Swift 5 at some point?

**Comment by morganchen12** [comment]
Looks like the fix may have to come from MaterialComponents.

**Comment by ulukaya** [comment]
Fixed the issue on https://github.com/firebase/friendlypix-ios/commit/fa0131fa50fd0f83add308e93c817e924aaeb8ed#diff-aa98627c956e501e6343aaa8732a9bad
