### ISSUE TITLE
Frequent NSInternalConsistencyException Crashes

### ISSUE THREAD

**Issue by hamachikama88** [firebase/friendlypix-ios#43]
Hello, first of all, just wanted to say that Ibrahim and the rest of the team at Google that worked on FriendlyPix did a wonderful job!

I am forking the FriendlyPix iOS code for a side project and noticed that the app crashes quite often due to an "NSInternalInconsistencyException". It seems that when items in the feed are added or deleted (especially the more users there are concurrently using the feed), this error will crash the app. Here are some examples:

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete item 2 from section 0 which only contains 1 items before the update'

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections. The number of sections contained in the collection view after the update (16) must be equal to the number of sections contained in the collection view before the update (18), plus or minus the number of sections inserted or deleted (1 inserted, 1 deleted).'

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete section 4, but there are only 4 sections before the update'

Would you happen to know how this can be fixed? It's a difficult bug to reproduce consistently as it just seems to happen randomly. I have tried implementing some fixes that others have suggested online related to collection view-related crashes, but to no avail. Thanks so much in advance!

**Comment by samtstern** [comment]
@hamachikama88 thanks for the feedback!  Did you intend to close this issue?
